### ISSUE TITLE
More docs 

### ISSUE THREAD

**Issue by isAlmogK** [Meteor-Community-Packages/Meteor-EventEmitter#1]
Would be nice to get some more docs and examples or guides.

**Comment by zimt28** [comment]
And maybe some use cases :)

**Comment by derwaldgeist** [comment]
+1
I tried to understand what this package does, and also had a look at the Node docs. But these are referring to a lot of Node-specific stuff that I am not familiar with.
For instance, my quite basic question is: Does this even emitting also work across the client-server boundary, or does it only work on one side of the fence?

**Comment by Sojourneer** [comment]
+1
I am also looking use this to cleanly implement Accounts.onCreate on the client side

**Comment by Sojourneer** [comment]
As far as I can see:

- emit from server is received on server and client
- emit from client is only received on client
