### ISSUE TITLE
Publishing permissions

### ISSUE THREAD

**Issue by jankapunkt** [Meteor-Community-Packages/Meteor-EventEmitter#16]
I got during `meteor publish`

```shell
While pre-publishing package raix:eventemitter:
error: You are not an authorized maintainer for this package.
```

@StorytellerCZ did MCP got added during transfer?

Background: I wanted to publish a compat release, together with a deprecated flag

**Comment by StorytellerCZ** [comment]
I don't know, I don't think I was directly involved in getting this here, if at all.

**Comment by StorytellerCZ** [comment]
I don't see us on Galaxy, so I think we need to ask @raix to add MCP there.

**Comment by raix** [comment]
Not sure I have access anymore will check 🤔  - maybe @meteor or @tmeasday could help out?

**Comment by jankapunkt** [comment]
@StorytellerCZ is this resolved?

**Comment by StorytellerCZ** [comment]
Should be, please check if it works for you now.
